idf_component_register(
    SRCS
        "blink_example_main.cpp"
        "model_data.c"
    INCLUDE_DIRS
        "."
        "${CMAKE_CURRENT_SOURCE_DIR}/../managed_components/espressif__esp-tflite-micro/examples/micro_speech/main"
    REQUIRES
        esp_driver_i2s
        esp_driver_gpio
        esp_driver_uart
        esp-tflite-micro
)
